angular.module("AFootball")
	.directive('teamchartoffense', function() {
    return {
		scope: { gamedata: '=' },
		templateUrl: "teamchartoffense.html",
        link: function(scope, elem, attrs) {

			scope.results = [
				{ lineno: 10, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "2" },
					{ bgcolor: "white",  text: "3" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "2" },
					{ bgcolor: "white",  text: "3" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "2" },
					{ bgcolor: "white",  text: "3" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "2" },
					{ bgcolor: "white",  text: "3" },
				]},
				{ lineno: 11, results: [
					{ bgcolor: "green",  text: "2" },
					{ bgcolor: "red",  text: "3" },
					{ bgcolor: "white",  text: "4" },
					{ bgcolor: "green",  text: "2" },
					{ bgcolor: "red",  text: "3" },
					{ bgcolor: "white",  text: "4" },
					{ bgcolor: "green",  text: "2" },
					{ bgcolor: "red",  text: "3" },
					{ bgcolor: "white",  text: "4" },
					{ bgcolor: "green",  text: "2" },
					{ bgcolor: "red",  text: "3" },
					{ bgcolor: "white",  text: "4" },
				] },
				{ lineno: 12, results: [
					{ bgcolor: "green",  text: "3" },
					{ bgcolor: "red",  text: "4" },
					{ bgcolor: "white",  text: "5" },
					{ bgcolor: "green",  text: "3" },
					{ bgcolor: "red",  text: "4" },
					{ bgcolor: "white",  text: "5" },
					{ bgcolor: "green",  text: "3" },
					{ bgcolor: "red",  text: "4" },
					{ bgcolor: "white",  text: "5" },
					{ bgcolor: "green",  text: "3" },
					{ bgcolor: "red",  text: "4" },
					{ bgcolor: "white",  text: "5" },
				] },
				{ lineno: 13, results: [
					{ bgcolor: "green",  text: "4" },
					{ bgcolor: "red",  text: "5" },
					{ bgcolor: "white",  text: "6" },
					{ bgcolor: "green",  text: "4" },
					{ bgcolor: "red",  text: "5" },
					{ bgcolor: "white",  text: "6" },
					{ bgcolor: "green",  text: "4" },
					{ bgcolor: "red",  text: "5" },
					{ bgcolor: "white",  text: "6" },
					{ bgcolor: "green",  text: "4" },
					{ bgcolor: "red",  text: "5" },
					{ bgcolor: "white",  text: "6" },
				] },
				{ lineno: 14, results: [
					{ bgcolor: "green",  text: "5" },
					{ bgcolor: "red",  text: "6" },
					{ bgcolor: "white",  text: "7" },
					{ bgcolor: "green",  text: "5" },
					{ bgcolor: "red",  text: "6" },
					{ bgcolor: "white",  text: "7" },
					{ bgcolor: "green",  text: "5" },
					{ bgcolor: "red",  text: "6" },
					{ bgcolor: "white",  text: "7" },
					{ bgcolor: "green",  text: "5" },
					{ bgcolor: "red",  text: "6" },
					{ bgcolor: "white",  text: "7" },
				] },
				{ lineno: 15, results: [
					{ bgcolor: "green",  text: "6" },
					{ bgcolor: "red",  text: "7" },
					{ bgcolor: "white",  text: "8" },
					{ bgcolor: "green",  text: "6" },
					{ bgcolor: "red",  text: "7" },
					{ bgcolor: "white",  text: "8" },
					{ bgcolor: "green",  text: "6" },
					{ bgcolor: "red",  text: "7" },
					{ bgcolor: "white",  text: "8" },
					{ bgcolor: "green",  text: "6" },
					{ bgcolor: "red",  text: "7" },
					{ bgcolor: "white",  text: "8" },
				] },
				{ lineno: 16, results: [
					{ bgcolor: "green",  text: "7" },
					{ bgcolor: "red",  text: "8" },
					{ bgcolor: "white",  text: "9" },
					{ bgcolor: "green",  text: "7" },
					{ bgcolor: "red",  text: "8" },
					{ bgcolor: "white",  text: "9" },
					{ bgcolor: "green",  text: "7" },
					{ bgcolor: "red",  text: "8" },
					{ bgcolor: "white",  text: "9" },
					{ bgcolor: "green",  text: "7" },
					{ bgcolor: "red",  text: "8" },
					{ bgcolor: "white",  text: "9" },
				] },
				{ lineno: 17, results: [
					{ bgcolor: "green",  text: "8" },
					{ bgcolor: "red",  text: "9" },
					{ bgcolor: "white",  text: "10" },
					{ bgcolor: "green",  text: "8" },
					{ bgcolor: "red",  text: "9" },
					{ bgcolor: "white",  text: "10" },
					{ bgcolor: "green",  text: "8" },
					{ bgcolor: "red",  text: "9" },
					{ bgcolor: "white",  text: "10" },
					{ bgcolor: "green",  text: "8" },
					{ bgcolor: "red",  text: "9" },
					{ bgcolor: "white",  text: "10" },
				] },
				{ lineno: 18, results: [
					{ bgcolor: "green",  text: "9" },
					{ bgcolor: "red",  text: "10" },
					{ bgcolor: "white",  text: "11" },
					{ bgcolor: "green",  text: "9" },
					{ bgcolor: "red",  text: "10" },
					{ bgcolor: "white",  text: "11" },
					{ bgcolor: "green",  text: "9" },
					{ bgcolor: "red",  text: "10" },
					{ bgcolor: "white",  text: "11" },
					{ bgcolor: "green",  text: "9" },
					{ bgcolor: "red",  text: "10" },
					{ bgcolor: "white",  text: "11" },
				] },
				{ lineno: 19, results: [
					{ bgcolor: "green",  text: "10" },
					{ bgcolor: "red",  text: "11" },
					{ bgcolor: "white",  text: "12" },
					{ bgcolor: "green",  text: "10" },
					{ bgcolor: "red",  text: "11" },
					{ bgcolor: "white",  text: "12" },
					{ bgcolor: "green",  text: "10" },
					{ bgcolor: "red",  text: "11" },
					{ bgcolor: "white",  text: "12" },
					{ bgcolor: "green",  text: "10" },
					{ bgcolor: "red",  text: "11" },
					{ bgcolor: "white",  text: "12" },
				] },
				{ lineno: 20, results: [
					{ bgcolor: "green",  text: "11" },
					{ bgcolor: "red",  text: "12" },
					{ bgcolor: "white",  text: "13" },
					{ bgcolor: "green",  text: "11" },
					{ bgcolor: "red",  text: "12" },
					{ bgcolor: "white",  text: "13" },
					{ bgcolor: "green",  text: "11" },
					{ bgcolor: "red",  text: "12" },
					{ bgcolor: "white",  text: "13" },
					{ bgcolor: "green",  text: "11" },
					{ bgcolor: "red",  text: "12" },
					{ bgcolor: "white",  text: "13" },
				] },
				{ lineno: 21, results: [
					{ bgcolor: "green",  text: "12" },
					{ bgcolor: "red",  text: "13" },
					{ bgcolor: "white",  text: "14" },
					{ bgcolor: "green",  text: "12" },
					{ bgcolor: "red",  text: "13" },
					{ bgcolor: "white",  text: "14" },
					{ bgcolor: "green",  text: "12" },
					{ bgcolor: "red",  text: "13" },
					{ bgcolor: "white",  text: "14" },
					{ bgcolor: "green",  text: "12" },
					{ bgcolor: "red",  text: "13" },
					{ bgcolor: "white",  text: "14" },
				] },
				{ lineno: 22, results: [
					{ bgcolor: "green",  text: "13" },
					{ bgcolor: "red",  text: "14" },
					{ bgcolor: "white",  text: "15" },
					{ bgcolor: "green",  text: "13" },
					{ bgcolor: "red",  text: "14" },
					{ bgcolor: "white",  text: "15" },
					{ bgcolor: "green",  text: "13" },
					{ bgcolor: "red",  text: "14" },
					{ bgcolor: "white",  text: "15" },
					{ bgcolor: "green",  text: "13" },
					{ bgcolor: "red",  text: "14" },
					{ bgcolor: "white",  text: "15" },
				] },
				{ lineno: 23, results: [
					{ bgcolor: "green",  text: "14" },
					{ bgcolor: "red",  text: "15" },
					{ bgcolor: "white",  text: "16" },
					{ bgcolor: "green",  text: "14" },
					{ bgcolor: "red",  text: "15" },
					{ bgcolor: "white",  text: "16" },
					{ bgcolor: "green",  text: "14" },
					{ bgcolor: "red",  text: "15" },
					{ bgcolor: "white",  text: "16" },
					{ bgcolor: "green",  text: "14" },
					{ bgcolor: "red",  text: "15" },
					{ bgcolor: "white",  text: "16" },
				] },
				{ lineno: 24, results: [
					{ bgcolor: "green",  text: "15" },
					{ bgcolor: "red",  text: "16" },
					{ bgcolor: "white",  text: "17" },
					{ bgcolor: "green",  text: "15" },
					{ bgcolor: "red",  text: "16" },
					{ bgcolor: "white",  text: "17" },
					{ bgcolor: "green",  text: "15" },
					{ bgcolor: "red",  text: "16" },
					{ bgcolor: "white",  text: "17" },
					{ bgcolor: "green",  text: "15" },
					{ bgcolor: "red",  text: "16" },
					{ bgcolor: "white",  text: "17" },
				] },
				{ lineno: 25, results: [
					{ bgcolor: "green",  text: "16" },
					{ bgcolor: "red",  text: "17" },
					{ bgcolor: "white",  text: "18" },
					{ bgcolor: "green",  text: "16" },
					{ bgcolor: "red",  text: "17" },
					{ bgcolor: "white",  text: "18" },
					{ bgcolor: "green",  text: "16" },
					{ bgcolor: "red",  text: "17" },
					{ bgcolor: "white",  text: "18" },
					{ bgcolor: "green",  text: "16" },
					{ bgcolor: "red",  text: "17" },
					{ bgcolor: "white",  text: "18" },
				] },
				{ lineno: 26, results: [
					{ bgcolor: "green",  text: "17" },
					{ bgcolor: "red",  text: "18" },
					{ bgcolor: "white",  text: "19" },
					{ bgcolor: "green",  text: "17" },
					{ bgcolor: "red",  text: "18" },
					{ bgcolor: "white",  text: "19" },
					{ bgcolor: "green",  text: "17" },
					{ bgcolor: "red",  text: "18" },
					{ bgcolor: "white",  text: "19" },
					{ bgcolor: "green",  text: "17" },
					{ bgcolor: "red",  text: "18" },
					{ bgcolor: "white",  text: "19" },
				] },
				{ lineno: 27, results: [
					{ bgcolor: "green",  text: "18" },
					{ bgcolor: "red",  text: "19" },
					{ bgcolor: "white",  text: "20" },
					{ bgcolor: "green",  text: "18" },
					{ bgcolor: "red",  text: "19" },
					{ bgcolor: "white",  text: "20" },
					{ bgcolor: "green",  text: "18" },
					{ bgcolor: "red",  text: "19" },
					{ bgcolor: "white",  text: "20" },
					{ bgcolor: "green",  text: "18" },
					{ bgcolor: "red",  text: "19" },
					{ bgcolor: "white",  text: "20" },
				] },
				{ lineno: 28, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 29, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 30, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 31, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 32, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 33, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 34, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 35, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 36, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 37, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 38, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
				{ lineno: 39, results: [
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
					{ bgcolor: "green",  text: "1" },
					{ bgcolor: "red",  text: "1" },
					{ bgcolor: "white",  text: "1" },
				] },
			];
 
			scope.closeNav = function() {
				// console.log("closeNav");
		        document.getElementById("teamchartoffense").style.width = "0px";
			};
		}
    }
});